//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCosta.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empoyee
    {
        public decimal ID { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string DocSeries { get; set; }
        public string DocNumber { get; set; }
        public string Position { get; set; }
        public System.Guid DepartmentID { get; set; }
    
        public virtual Department Department { get; set; }

        public override string ToString()
        {
            return $"{SurName} {FirstName} {Patronymic}";
        }
    }
}
